### ISSUE TITLE
Reduce inconsistency about `html` option between `Marp` and `Marpit`

### ISSUE THREAD

**Issue by exKAZUu** [marp-team/marp-core#111]
`Marp` constructor ignores `markdown.html` option (c.f. https://github.com/marp-team/marp-core#html-boolean--object), but, `Marpit` constrcutor accepts `markdown.html` option (c.f. https://github.com/marp-team/marpit/blob/master/docs/usage.md#-markdown-it-parser-setting)

I feel this structure is a bit confusing. Could we unify `markdown.html` v.s. `html` ?

**Comment by yhatt** [comment]
Transferred issue from Marpit :arrow_forward: Marp Core 🚚

Surely it's confusable. Internally Marp Core's `html` option has already become just an alias to `markdown.html` by working at #74. It may be better to unify interface into `markdown.html` and match to Marpit.

### Background

Marp Core has an extra feature that there is not in Marpit, to sanitize HTML by whitelist if JSON was passed to html.

The reason why splitted options into html and markdown.html in Marp Core was afraid breaking compatibility with the other markdown-it plugins, because typically markdown-it's html option does allow boolean value only.
