### ISSUE TITLE
Tables Settings

### ISSUE THREAD

**Issue by eduardo4jesus** [marp-team/marp-core#155]
I am looking for a way to use tables to layout images in a single slide. But, to do it in a neat way, I would need to tackle some of the following features

- Table without header
- Header without being bold
- Table without borders
- Table without alternating background colour

Is there a way to do the things above that I am not currently aware of?

PS.: I've tried to do the table in pure html tags, it didn't seem to work.

**Comment by yhatt** [comment]
Using HTML tag such as `<table>` is disabled by default for security reason, so [you should turn on HTML tags in a way of Marp tool you're using](https://github.com/marp-team/marpit/issues/178#issuecomment-511106762). And you have to learn CSS and know [style of theme you're using](https://github.com/marp-team/marp-core/tree/master/themes) if you want to control the appearance of table.

It's are not difficult once you get used to these because it's looking just a same as webpage.

```html
---
marp: true
theme: gaia
---

<style scoped>
/* Reset table styling provided by theme */
table, tr, td, th {
  all: unset;

  /* Override contextual styling */
  border: 0 !important;
  background: transparent !important;
}
table { display: table; }
tr { display: table-row; }
td, th { display: table-cell; }

/* ...and layout freely :) */
table {
  width: 100%;
}
td {
  text-align: center;
  vertical-align: middle;
}
</style>

<table>
  <tr>
    <td>foo</td>
    <td><img src="https://fakeimg.pl/160x90/ccc/999/" /></td>
  </tr>
  <tr>
    <td><img src="https://fakeimg.pl/160x90/ccc/999/" /></td>
    <td>bar</td>
  </tr>
</table>
```

![rendered](https://user-images.githubusercontent.com/3993388/77032600-2b6b4180-69e8-11ea-9ef7-a7a99aba93d6.png)

**Comment by eduardo4jesus** [comment]
Awesome, thanks a lot. I spent a bit of time looking for how to enable the html. It is working!

**Comment by yhatt** [comment]
OK, mark as resolved. Enabling HTML allows some maliciouses such as script injection too, so use carefully!

**Comment by eduardo4jesus** [comment]
Just to make sure I am managing my risks properly. By malicious scripts, you mean in a scenario where I use `Marp` to compile a file which might have scripts embed into it?

Therefore, if I am writing and compiling my own files, that means that my risk is pretty much mitigated. Is that it?

**Comment by yhatt** [comment]
Yes, you're right. You might hardly worry some risks while editing your own file.

**Comment by eduardo4jesus** [comment]
Interesting to note that the style only works if put on the same page as the table. If I move it to the top of the file as part of the first page of the slide, it won't be applied.

**Comment by yhatt** [comment]
@eduardo4jesus Try `<style>` instead of `<style scoped>`. See [Marpit docs](https://marpit.marp.app/theme-css?id=tweak-style-through-markdown) for details.
