### ISSUE TITLE
MathJaX v3 support

### ISSUE THREAD

**Issue by nzt** [marp-team/marp-core#164]
Hi there, I am author of the following plugins

- MathJaX v3 plugin of VNote https://github.com/tamlok/vnote/pull/1221
- MathJaX v3 plugin of Remark https://github.com/remarkjs/remark-math/pull/40
- MathJaX v3 plugin of Markdown-It https://github.com/nzt/markdown-it-mathjax3

As I'd like to use MathJaX v3 in map-core, I open this issue. MathJaX v3 has a new plugin for bussproofs missing in the older versions, and also, has a SVG rendering without any fonts. There is good conformance for your project at the SVG feature.

 I've already implemented markdown-it plugin with TypeScript based on markdown-it-katex as like marp-core. Thus, I can add MathJaX plugin to your project immediately.

I'd like to ask you, which options do you choose?
1. Replacing KaTeX plugin with MathJaX plugin
2. Adding MathJaX plugin, and keeping KaTeX plugin

Thanks!

**Comment by yhatt** [comment]
Thanks for your suggestion. Due to slow rendering and not supported server-side rendering, we had given up using MathJax v2 in Marp. But [MathJax v3 seems to have got rid of many messy issues](https://docs.mathjax.org/en/latest/upgrading/whats-new-3.0.html).

And we had some requests about math typesettings, such as https://github.com/yhatt/marp/issues/103 and https://github.com/yhatt/marp/issues/181. They are not yet resolved by KaTeX's limitations and might be fix them by MathJax v3 integration.

I prefer option 2 to make compatibility with exist decks made with KaTeX.

**Comment by nzt** [comment]
Okay, check my pull request #165 . I've implemented option 2 because I also thought as you 😉

**Comment by yhatt** [comment]
_NOTE: Keep in mind that we require to support [auto-scaling in math block](https://github.com/marp-team/marp-core/blob/master/src/fitting/fitting.ts#L99-L123) when you will work for Marp Core integration._

**Comment by nzt** [comment]
At least, all tests are passed including a new test I added for auto-scaling in math block.
I just borrow all test code from your project.
