### ISSUE TITLE
Code block autoscaling does not work properly

### ISSUE THREAD

**Issue by siavashs** [marp-team/marp-core#190]
Thanks for creating Marp!
I've started using Marp and faced some issues with `code` auto-scaling with all themes:
- The `default` theme results in part of title and the last sentence to be chopped off because of bad positioning:
  ![image](https://user-images.githubusercontent.com/113189/93019537-e6f7e180-f5d7-11ea-9bc2-c63bb37ddf54.png)
- The `gaia` theme results in part of `code` block and the last sentence to chopped off because of bad scaling:
  ![image](https://user-images.githubusercontent.com/113189/93019594-4c4bd280-f5d8-11ea-9861-07236791fbb8.png)

Here are the global setting on my slides:
```yaml
marp: true
paginate: true
theme: gaia
class: invert
```

My code slide source:
```markdown
---
# Chunks
\```
-------------------------------------------------------------------
|        MagicNumber(4b)        |           version(1b)           |
-------------------------------------------------------------------
|         block-1 bytes         |          checksum (4b)          |
-------------------------------------------------------------------
|         block-2 bytes         |          checksum (4b)          |
-------------------------------------------------------------------
|         block-n bytes         |          checksum (4b)          |
-------------------------------------------------------------------
|                        #blocks (uvarint)                        |
-------------------------------------------------------------------
| #entries(uvarint) | mint, maxt (varint) | offset, len (uvarint) |
-------------------------------------------------------------------
| #entries(uvarint) | mint, maxt (varint) | offset, len (uvarint) |
-------------------------------------------------------------------
| #entries(uvarint) | mint, maxt (varint) | offset, len (uvarint) |
-------------------------------------------------------------------
| #entries(uvarint) | mint, maxt (varint) | offset, len (uvarint) |
-------------------------------------------------------------------
|                      checksum(from #blocks)                     |
-------------------------------------------------------------------
|                    #blocks section byte offset                  |
-------------------------------------------------------------------
\```
`mint` and `maxt` describe the minimum and maximum Unix nanosecond timestamp, respectively.
```

**Comment by yhatt** [comment]
[This is the limitation of Marp Core's auto-scaling.](https://github.com/marp-team/marp-core#:~:text=Marp%20Core%20won't%20detect%20whether%20they%20actually%20protrude%20from%20the%20slide.%20It%20might%20not%20work%20scaling%20correctly%20when%20there%20are%20many%20elements%20in%20a%20slide.) Each themes has [the fixed `max-height` size](https://github.com/marp-team/marp-core/blob/master/themes/default.scss#L14-L16). They are based on height size without other elements, such as headings and paragraphs, so too many codes make contents stick out from the slide.

_The most suitable scale for auto-scaled codes is too hard to determine_ because it would be affected from a lot of variable CSS styles: Positioning, Floating, Animation, multiple auto-scaling elements, and more.

As a workaround, you can manually set a suitable font-size for the code block into the current slide through [scoped style](https://marpit.marp.app/theme-css?id=scoped-style).

```html
<style scoped>
pre {
  font-size: 48%;
}
</style>
```

![marp](https://user-images.githubusercontent.com/3993388/93025857-6fa86900-f63c-11ea-8fe3-307dca4ac2bd.png)

**Comment by siavashs** [comment]
Thanks for your quick response, sorry that I missed the other issue.
Feel free to close this as a duplicate.
