### ISSUE TITLE
Combining Slides from Marp with existing PDF

### ISSUE THREAD

**Issue by ecoelhor** [marp-team/marp-core#192]
I don't think this feature exists, and I think it would be very helpful.

I have an existing lecture slide. I wish I could use Marp, which I currently do via VS Code, to write my own notes on top of the existing PDF. The nodes would be new slide pages. I imagining it could work something like this.

With the theme and other options within a MD file, I could point to an existing PDF.

Then, as we write an new slide page, we could have some special tag on it to determine how and where that slide would be added. For instance, we inform a page number, and if that slide should be added before or after that page number.

The page number references would be relative to the original slides.

Then, as we compile from `.md` to `.pdf` we would mix both original slides and the nodes we are adding.

Maybe another tag to remove a certain page, or page ranges could also be helpful.

What are your thoughts on that? Do you think that is helpful? Is that something already exists and I just did a bad search?

**Comment by yhatt** [comment]
The idea is interesting, but stirring PDF would be difficult because essentially Marp is _just a HTML generator_. We don't want to do some complex thing in Marp, for keeping our projects simple (Refer to [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) too).

Probably it's better as the extra tool for making a collage PDF from some PDFs. However, that would not be a goal that should achieve by Marp team.

**Comment by ecoelhor** [comment]
Thanks for the feedback, and reference about the [KISS principle](https://en.wikipedia.org/wiki/KISS_principle).
