### ISSUE TITLE
$a \xmapsto f b$ rendered different than mathjax

### ISSUE THREAD

**Issue by GoBigorGoHome** [marp-team/marp-core#388]
In mathjax, `$a \xmapsto f b$` is rendered as 
![image](https://github.com/user-attachments/assets/ecef21c3-b02a-42d2-a80c-4b69e039ffab)
One can use the live demo https://www.mathjax.org/#demo to check.
But in marp, `$a \xmapsto f b$` is rendered as
![image](https://github.com/user-attachments/assets/4c04439c-4a87-40bc-b09f-f18cfd08cdf4)

I guess the difference is caused by the converter.

Frontmatter of my markdown file is
```
---
marp: true
paginate: true
math: mathjax
---
```

**Comment by yhatt** [comment]
Marp uses SVG to render MathJax so the rendering may become slightly different from HTML. (The live demo uses HTML renderer)
https://github.com/marp-team/marp-core/blob/main/src/math/mathjax.ts

Since I am not a mathematician, I'm not so familiar with MathJax and I cannot fully grasp how important this slight difference in the glyph. If you're concerned about it, it might be good to consider [reporting the issue to MathJax](https://github.com/mathjax/MathJax/blob/master/CONTRIBUTING.md#reporting-an-issue).
